---
- name: Create directory for metr1c
  ansible.builtin.file:
    path: "{{ metr1c_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "Install metr1c if it is not present"
  ansible.builtin.get_url:
    url: "https://github.com/Doumor/metr1c/releases/download/{{ metr1c_version }}/metr1c"
    dest: /opt/metr1c/
    owner: root
    group: root
    mode: "0755"

- name: "Create systemd metr1c service file"
  ansible.builtin.template:
    src: "templates/metr1c.service.j2"
    dest: "/etc/systemd/system/metr1c.service"
    owner: root
    group: root
    mode: "0750"

- name: "Make sure that the timer service is started"
  become: true
  ansible.builtin.systemd:
    name: "metr1c.service"
    state: started
    enabled: true
    daemon_reload: true

